CREATE DATABASE IF NOT EXISTS SIGN;
USE SIGN;
CREATE TABLE IF NOT EXISTS providers(
    provider_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(35) NOT NULL,
    lastname  VARCHAR(35) NOT NULL,
    email VARCHAR(100),
    phone INTEGER UNSIGNED,
    image_url VARCHAR(255),
    about TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
        ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE IF NOT EXISTS services(
    service_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (50) NOT NULL,
    description TEXT,
    cost FLOAT NOT NULL,
    cost_per_hour FLOAT DEFAULT cost,
    provider_id INTEGER NOT NULL
)CHARACTER SET utf8 COLLATE utf8_spanish_ci;

CREATE TABLE IF NOT EXISTS products(
    product_id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (50) NOT NULL,
    description TEXT,
    cost FLOAT NOT NULL,
    provider_id INTEGER NOT NULL
)CHARACTER SET utf8 COLLATE utf8_spanish_ci;

